vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO lexbor/lexbor
    REF b2c0a617f3f3ccbef9b51aa8910711b75c45f903
    SHA512 e3026b778b4929ad24c0ea406fcbd707d3fc9d87bca134b5cec10f54c71c14d6c893a1e1cef033fce8e4883bceb2c2786276612af312d16cde3e6c994b9ebab2
)

string(COMPARE EQUAL ${VCPKG_LIBRARY_LINKAGE} static LEXBOR_BUILD_STATIC)
string(COMPARE EQUAL ${VCPKG_LIBRARY_LINKAGE} dynamic LEXBOR_BUILD_SHARED)
vcpkg_configure_cmake(
    SOURCE_PATH ${SOURCE_PATH}
    OPTIONS
        -DLEXBOR_BUILD_STATIC=${LEXBOR_BUILD_STATIC}
        -DLEXBOR_BUILD_SHARED=${LEXBOR_BUILD_SHARED}
    PREFER_NINJA
)

vcpkg_install_cmake()

file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/debug/include)
file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/include/${PORT}/html/tree/insertion_mode)

file(
    INSTALL ${CMAKE_CURRENT_LIST_DIR}/${PORT}-config.cmake
    DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT}
)
file(
    INSTALL ${SOURCE_PATH}/LICENSE
    DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT}
    RENAME copyright
)
